!munch.Munch
dataset: dataset/denoiser_dataset
work_dir: exp_shapeNet_shape_lvl/
batch_size: 28
model_name: AdaPoinTr # point2ssm # pointsdenoiser  # pointTr # PointTransformerEncoderEntry # displacement_res_deform
device: cuda:0
epochs: 2000
added_noise_dim: 1500
coarse_to_fine: False
encoder: PointTransformerEncoderEntry #local_pool_pointnet # dgcnn # PointTransformerEncoderEntry

num_query: 512
num_points: 8192
center_num: [512, 256]
global_feature_dim: 1024
encoder_type: graph
decoder_type: fc

encoder_config: {
      embed_dim: 384,
      depth: 6,
      num_heads: 6,
      k: 8,
      n_group: 2,
      mlp_ratio: 2.,
      block_style_list: ['attn-graph', 'attn', 'attn', 'attn', 'attn', 'attn'], 
      combine_style: 'concat',
    }


decoder_config:
      {
        embed_dim: 384,
        depth: 8,
        num_heads: 6,
        k: 8,
        n_group: 2,
        mlp_ratio: 2.,
        self_attn_block_style_list:
          [
            "attn-graph",
            "attn",
            "attn",
            "attn",
            "attn",
            "attn",
            "attn",
            "attn",
          ],
        self_attn_combine_style: "concat",
        cross_attn_block_style_list:
          [
            "attn-graph",
            "attn",
            "attn",
            "attn",
            "attn",
            "attn",
            "attn",
            "attn",
          ],
        cross_attn_combine_style: "concat",
      }

data:
  dataset: Shapes3D
  path: data/ShapeNet
  class: null
  data_type: psr_full
  input_type: pointcloud
  dim: 3
  num_points: 2048
  num_gt_points: 5000
  num_offset: 1
  img_size: null
  n_views_input: 20
  n_views_per_iter: 2
  pointcloud_noise: 0
  pointcloud_file: pointcloud.npz
  pointcloud_outlier_ratio: 0
  fixed_scale: 0
  train_split: train
  val_split: val
  test_split: test
  points_file: null
  points_iou_file: points.npz
  points_unpackbits: true
  padding: 0.1
  multi_files: null
  gt_mesh: null
  zero_level: 0
  only_single: False
  sample_only_floor: False




alpha: 0.01
lat_dims: 64 # 64
lat_high_freq_dims: 8 # 64
local_dim: 64
latent_dim: 128
num_input_points: 2048
num_output_points: 256 #2048
deformer_nf: 64 # 80? 96? 128?
guidance_interpolation: 2
n_clusters: 4
solver: 'dopri5'
adjoint: True
arch: "imnet" # "imnet"
nonlin: 'leakyrelu'
rtol: 0.0001
atol: 0.0001
via_hub: False
symm: False
return_waypoints: False
use_latent_waypoints: False

loss: cd_t
nepoch: 3000
early_stop: True
early_stop_patience: 100
early_stop_start: 0

optimizer: AdamW
betas: 0.9, 0.999
lr: 0.0001
lr_decay: False

manual_seed: 42
weight_decay: 0
workers: 0

epoch_interval_to_save: 10
epoch_interval_to_val: 1
step_interval_to_print: 400

save_predictions: true
load_model: null
start_epoch: 0