!munch.Munch
dataset: dataset/part_chair_leg_pca64
work_dir: exp_shapeNet_chair_leg/
batch_size: 2
model_name: displacement_flow_siren # displacement_flow # dgcnn_transfomer
device: cuda:0
epochs: 2000
coarse_to_fine: False
lat_dims: 16 # 64
num_input_points: 1024
deformer_nf: 32 # 80? 96? 128?
guidance_interpolation: 2
n_clusters: 4
solver: 'dopri5'
adjoint: True
arch: "Siren" # "imnet"
nonlin: 'leakyrelu'
rtol: 0.0001
atol: 0.0001
via_hub: False
symm: False
return_waypoints: False
use_latent_waypoints: False

# input_size: 3
# hidden_size: 512
# num_layers: 3
# output_size: 3
# pca_dim: 64
# num_mapping_layers: 2


# latent_dim: 128
# num_output_points: 1024


loss: cd_t
nepoch: 3000
early_stop: True
early_stop_patience: 100
early_stop_start: 0

optimizer: AdamW
betas: 0.9, 0.999
lr: 0.001
lr_decay: False

manual_seed: 42
weight_decay: 0
workers: 0

epoch_interval_to_save: 10
epoch_interval_to_val: 1
step_interval_to_print: 400

save_predictions: true
load_model: null
start_epoch: 0